FROM gcc:4.9
WORKDIR /app

COPY ./peer /app/torrents/peer
COPY ./common /app/torrents/common

RUN gcc -std=gnu11 -O2 -Wall -Wextra -pthread -o /app/tpeer \
	/app/torrents/peer/main.c \
	/app/torrents/common/proto_net.c \
	/app/torrents/common/proto_codec.c \
	/app/torrents/common/proto_bitfield.c \
	/app/torrents/common/proto_msg.c
CMD ["/app/tpeer", "serve"]
