FROM gcc:4.9
WORKDIR /app

# was: COPY . /app/torrents/tracker
COPY ./tracker /app/torrents/tracker
# was: COPY ../common /app/torrents/common
COPY ./common /app/torrents/common

RUN gcc -std=gnu11 -O2 -Wall -Wextra -o /app/tracker \
	/app/torrents/tracker/main.c \
	/app/torrents/common/proto_net.c \
	/app/torrents/common/proto_codec.c \
	/app/torrents/common/proto_bitfield.c \
	/app/torrents/common/proto_msg.c \
	/app/torrents/common/proto_resume.c \
	/app/torrents/common/proto_sha256.c
CMD ["/app/tracker", "9000"]
