FROM gcc:4.9
WORKDIR /app

# was: COPY . /app/torrents/tracker
COPY ./tracker /app/torrents/tracker
# was: COPY ../common /app/torrents/common
COPY ./common /app/torrents/common

RUN gcc -std=gnu11 -O2 -Wall -Wextra -o /app/tracker /app/torrents/tracker/main.c /app/torrents/common/proto.c
CMD ["/app/tracker", "9000"]
